"""大改

Revision ID: 00e9cb53deb6
Revises: b18076592822
Create Date: 2025-08-25 17:47:37.745912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00e9cb53deb6'
down_revision: Union[str, Sequence[str], None] = 'b18076592822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('model_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ai_models', 'models', ['model_id'], ['id'])
    op.drop_column('ai_models', 'platform_name')
    op.drop_column('ai_models', 'model_name')
    op.alter_column('api_logs', 'request_params',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('api_logs', 'response',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('conversations', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('conversations', 'content')
    op.alter_column('document_history', 'content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4000),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('messages', sa.Column('docx_file', sa.String(length=255), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2000),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('platforms', sa.Column('base_url', sa.String(length=255), nullable=False))
    op.add_column('platforms', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('platforms', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('platforms', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('templates', 'content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4000),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4000),
               existing_nullable=True)
    op.drop_column('platforms', 'created_at')
    op.drop_column('platforms', 'is_active')
    op.drop_column('platforms', 'description')
    op.drop_column('platforms', 'base_url')
    op.alter_column('messages', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2000),
               existing_nullable=True)
    op.drop_column('messages', 'docx_file')
    op.alter_column('document_history', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4000),
               existing_nullable=True)
    op.add_column('conversations', sa.Column('content', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=True))
    op.alter_column('conversations', 'title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    op.alter_column('api_logs', 'response',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=True)
    op.alter_column('api_logs', 'request_params',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=True)
    op.add_column('ai_models', sa.Column('model_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('ai_models', sa.Column('platform_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_constraint(None, 'ai_models', type_='foreignkey')
    op.drop_column('ai_models', 'model_id')
    # ### end Alembic commands ###
