"""delete columns

Revision ID: 3e825659ea2a
Revises: 9e798574e6c0
Create Date: 2025-08-24 17:35:35.064848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e825659ea2a'
down_revision: Union[str, Sequence[str], None] = '9e798574e6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('platform_name', sa.String(length=100), nullable=False))
    op.add_column('ai_models', sa.Column('model_name', sa.String(length=100), nullable=False))
    op.add_column('ai_models', sa.Column('api_key', sa.String(length=255), nullable=False))
    op.add_column('ai_models', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('ai_models', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('ai_models', 'model_type')
    op.drop_column('ai_models', 'training_data')
    op.drop_column('ai_models', 'name')
    op.drop_column('ai_models', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('ai_models', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('ai_models', sa.Column('training_data', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
    op.add_column('ai_models', sa.Column('model_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_column('ai_models', 'updated_at')
    op.drop_column('ai_models', 'created_at')
    op.drop_column('ai_models', 'api_key')
    op.drop_column('ai_models', 'model_name')
    op.drop_column('ai_models', 'platform_name')
    # ### end Alembic commands ###
