"""add base_url in AI_Model

Revision ID: b18076592822
Revises: 61f8a0f4ab9f
Create Date: 2025-08-25 16:29:19.806065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18076592822'
down_revision: Union[str, Sequence[str], None] = '61f8a0f4ab9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('base_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_models', 'base_url')
    # ### end Alembic commands ###
